### ISSUE TITLE
[Feature Request] add notification support

### ISSUE THREAD

**Issue by MegaloDawn** [PretendoNetwork/nimbus#11]
So when I was on my 3ds, I thought "hey, Nintendo doesn't use the notifications anymore after the 3ds and Wii U was discontinued with the last one being the E shop, so what if Pretendo adds notification support to show server updates or show when a pubic beta comes out as it feels a bit lifeless when you go on it"

**Comment by jonbarrow** [comment]
Notifications are sent over SpotPass, which is done via the BOSS server. This is not a Nimbus issue, and we have already begun sending notifications. Sending entire blog posts is likely not possible due to their size/complexity (images, videos, etc.) but we are able to alert players of new updates via smaller notifications
