### ISSUE TITLE
Badge deletion issues with PNID

### ISSUE THREAD

**Issue by benny-dreamly** [PretendoNetwork/nimbus#34]
https://github.com/PretendoNetwork/Pretendo/issues/52

**Comment by snoozbuster** [comment]
I don't think this original issue is very good, cause it doesn't really really have anything to do with nimbus. I'd like to hijack it to inquire about something which is possibly related to the project. 

Someone [suggested](https://discord.com/channels/408718485913468928/1227137764529803294/1228400516787212360) in the discord server that it would be a neat feature if nimbus could automatically update the persistent ID stored in the badge data when switching between accounts. I don't know if this exactly falls under the scope of nimbus but it would definitely make the transition between the two accounts much more seamless, especially because it's not possible (as far as I'm aware) to have separate badge data on the two accounts.

**Comment by benny-dreamly** [comment]
Yeah. I saw that someone had a PR for the website to add a disclaimer so I think this issue can be closed here as it doesn’t really concern nimbus much.
