### ISSUE TITLE
[Feature]: Post blogs in Notification Center if possible

### ISSUE THREAD

**Issue by ProjectDreadman** [PretendoNetwork/nimbus#49]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

I want to see if it's possible to add the Pretendo blogs can be posted in the Notification Center for people to see (I already know I asked the same thing for inkey, but I want to see if it's possible on 3DS too)

### Why do you want to have this feature?

So it will be easier and more simpler for people to check out the blogs. Like if they don't have access to web browser they can just go to the notification center and check out the blogs and see what new features and games have been added. (also I understand that the 3DS might not handle all the images in the blogs and if it comes to that it can just be text only)

**Comment by jonbarrow** [comment]
Notifications are sent over SpotPass, which is done via the BOSS server. This is not a Nimbus issue, and we have already begun sending notifications. Sending entire blog posts is likely not possible due to their size/complexity (images, videos, etc.) but we are able to alert players of new updates via smaller notifications

**Comment by ProjectDreadman** [comment]
Ok mb
